version: "3"

dotenv:
  - .env

tasks:

  compile:
    cmds:
      - GOOS=linux go build -o ./bin/appapi ./cmd/api/
      - GOOS=linux go build -o ./bin/appinfo ./cmd/info/
      - GOOS=linux go build -o ./bin/applogin ./cmd/login/

  build:
    cmds:
      - docker build -f cmd/api/dockerfile -t appapi:latest .
      - docker build -f cmd/info/dockerfile -t appinfo:latest .
      - docker build -f cmd/login/dockerfile -t applogin:latest .


  deploy:
    cmds:
      - kubectl apply -f ./deployments/k8s/config-conf.yaml
      - kubectl apply -f ./deployments/k8s/deployment-nginx.yaml
      - kubectl apply -f ./deployments/k8s/dep-api/config-env-api.yaml 
      - kubectl apply -f ./deployments/k8s/dep-info/config-env-info.yaml 
      - kubectl apply -f ./deployments/k8s/dep-login/config-env-login.yaml 
      - kubectl apply -f ./deployments/k8s/dep-api/deployment-api.yaml
      - kubectl apply -f ./deployments/k8s/dep-info/deployment-info.yaml
      - kubectl apply -f ./deployments/k8s/dep-login/deployment-login.yaml


  release:
    cmds:
      - task: compile
      - task: build
      - task: deploy